<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="copy-right">
  <div class="container clearfix">
    <p><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></p>
    <div class="payment-links">
      <ul>
        <li><a href="#">
                <img src="<?php echo $block->getViewFileUrl('images/payments.png'); ?>">
            </a></li>
      </ul>
    </div>
  </div>
</div>