<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
//ini_set('display_errors', 1);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$checkoutSession = $objectManager->create('\Magento\Checkout\Model\Session');
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
//
$getSusbcriptionDays = $checkoutSession->getSusbcriptionDays();
$SusbcriptionDays = 20;
if (!is_null($getSusbcriptionDays)) {
    $SusbcriptionDays = $getSusbcriptionDays;
}
$DynamicBoxes = $checkoutSession->getDynamicBox();
$SavedDynamicBoxes = $checkoutSession->getSavedDynamicBox();
echo '<pre>'.var_export($DynamicBoxes, true).'</pre>';
echo 'test';
echo '<pre>' . var_export($SavedDynamicBoxes, true) . '</pre>';
echo 'test';
if (is_null($DynamicBoxes)) {
    header('Location:' . $this->getUrl() . 'tavia');
    die();
}
/*
  if (@$_GET) {
  if (@$_GET['tempons_sum'])
  $checkoutSession->setTempons($_GET['tempons_sum']);
  if (@$_GET['pads_sum'])
  $checkoutSession->setPads($_GET['pads_sum']);
  if (@$_GET['liners_sum'])
  $checkoutSession->setLiners($_GET['liners_sum']);
  if (@$_GET['total_sum'])
  $checkoutSession->setTotal($_GET['total_sum']);
  } */
?>
<?php
$objectManagers = \Magento\Framework\App\ObjectManager::getInstance();
$productRepositorys = $objectManagers->get('\Magento\Catalog\Model\ProductRepository');
$priceHelper = $objectManagers->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
$product = $productRepositorys->getById(183);
$selectionCollection = $product->getTypeInstance(true)->getSelectionsCollection($product->getTypeInstance(true)->getOptionsIds($product), $product);
$optionsCollection = $product->getTypeInstance(true)->getOptionsCollection($product);
foreach ($optionsCollection as $options) {
    if ($options->getDefaultTitle() == 'Box Type' && $options->getType() == 'radio') {
        $boxOptionId = $options->getOptionId();
    }
}
$optionhtml = '';
foreach ($selectionCollection as $proselection) {
    if ($proselection->getOptionId() == $boxOptionId) {
        //var_dump($proselection->getData());die();
        //$selectionArray = [];
        //$selectionArray['label'] = $proselection->getName();
        //$selectionArray['value'] = $proselection->getPrice();
        //$selectionArray['value'] = $proselection->getSku();
        //$selectionArray['price'] = $proselection->getSelectionQty();
        //$selectionArray['id'] = $proselection->getProductId();
        //$selectionArray['id'] = $proselection->getSelectionId();
        //$productsArray[$proselection->getOptionId()][$proselection->getSelectionId()] = $selectionArray;

        $optionhtml .= '<option data-id="' . $proselection->getSelectionId() . '" value="' . $proselection->getSku() . '">' . $proselection->getName() . ' - ' . $priceHelper->currency($proselection->getSelectionPriceValue(), true, false) . '</option>';
    }
}
?>
<form name="page1" action="" method="POST">
    <div class="container">
        <div class="tab-content">

            <div id="menu2" class="tab-pane fade in active">


                <div class="product-details customize-block">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="product-header ">
                                <h2> Create  <strong>your 
                                        <?php
                                        $formatter = new NumberFormatter('en_US', NumberFormatter::SPELLOUT);
                                        $formatter->setTextAttribute(NumberFormatter::DEFAULT_RULESET, "%spellout-ordinal");
                                        foreach ($DynamicBoxes as $DynamicBoxkey => $DynamicBoxval) {
                                            ?>
                                            <a href="javascript:;" id="<?php echo $formatter->format($DynamicBoxkey + 1) . PHP_EOL; ?>Box" class="dynamicboxlink" data-group="<?php echo $DynamicBoxkey; ?>"><?php echo $formatter->format($DynamicBoxkey + 1) . PHP_EOL; ?> box</a>
                                        <?php } ?>
                                </h2>
                                <h5>
                                    <a class="addextrabox" href="javascript:;"><i class="fa fa-refresh fa-spin loadericon1" style="display: none"></i>+ add an extra box</a>
                                </h5>
                            </div>
                            <?php
                            $show = true;
                            $ind = 1;
                            foreach ($DynamicBoxes as $DynamicBoxkey => $DynamicBoxval) {
                                ?>
                                <div class="table-responsive tr-responsive dynamicboxwrap" <?php
                                if ($ind == count($DynamicBoxes)) {
                                    
                                } else {
                                    echo 'style="display:none;"';
                                }
                                ?> data-group="<?php echo $DynamicBoxkey; ?>">
                                    <table class="table table-box">
                                        <tbody>
                                            <tr class="recomended-block">
                                                <td class="title-block">
                                                    <span><img src="<?php echo $this->getViewFileUrl('images/create-icon-1.png'); ?>"></span>Selected quantity
                                                </td>
                                                <td class="plus_minus">
                                                    <!--<a class="incr-btn" data-action="decrease" href="javascript:;">–</a>-->
                                                    <input  readonly="" class="s_item l_item ttl_qty" data-max="50" data-group="<?php echo $DynamicBoxkey; ?>"  type="text" name="total_sum" value="<?php echo $DynamicBoxval['Total']; ?>"/>
                                                    <!--<a class="incr-btn" data-action="increase" href="javascript:;">&plus;</a>-->
                                                </td>
                                                <td class="box-size">recommended box size
                                                    <select class="box_size_id" name="box_size" data-group="<?php echo $DynamicBoxkey; ?>">
                                                        <?php echo $optionhtml; ?>
                                                        <!--option value="15">15 Item box - $17</option>
                                                        <option value="20">20 Item box - $19</option>
                                                        <option value="25">25 Item box - $21</option>
                                                        <option value="50">50 Item box - $40</option-->
                                                    </select>
                                                </td>

                                        <div class="alert info-section alert-info">
                                            You have selected a <span class="ttl_box_display_qty" data-group="<?php echo $DynamicBoxkey; ?>">50</span> box Item and added <span class="ttl_display_added_qty" data-group="<?php echo $DynamicBoxkey; ?>" >50</span> items
                                        </div>


                                        </tr>
                                        <tr class="responsivehide" style="display: none">
                                            <td class="box-size">recommended box size</td>
                                            <td class="box-size">
                                                <select class="box_size_id" name="box_size" data-group="<?php echo $DynamicBoxkey; ?>">
                                                    <?php echo $optionhtml; ?>
                                                    <!--option value="15">15 Item box - $17</option>
                                                    <option value="20">20 Item box - $19</option>
                                                    <option value="25">25 Item box - $21</option>
                                                    <option value="50">50 Item box - $40</option-->
                                                </select>
                                            </td>

                                        <div class="alert info-section alert-info">
                                            You have selected a <span class="ttl_box_display_qty" data-group="<?php echo $DynamicBoxkey; ?>">50</span> box Item and added <span class="ttl_display_added_qty" data-group="<?php echo $DynamicBoxkey; ?>" >50</span> items
                                        </div>

                                        </tr>

                                        <tr class="ttl_cls Tampons_append" data-class="Tampons_append" data-group="<?php echo $DynamicBoxkey; ?>">
                                            <td class="title-block">
                                                <span><img src="<?php echo $this->getViewFileUrl('images/create-icon-2.png'); ?>"></span>Tampons
                                            </td>

                                            <?php $category = 'Tampons'; ?>
                                            <?php
                                            $sum = 0;
                                            if ($SavedDynamicBoxes) {
                                                ?>
                                                <?php if (array_key_exists($DynamicBoxkey, $SavedDynamicBoxes)) { ?>
                                                    <?php if (array_key_exists($category, $SavedDynamicBoxes[$DynamicBoxkey])) { ?>
                                                        <?php foreach ($SavedDynamicBoxes[$DynamicBoxkey][$category] as $pId => $SavedDynamicBoxval) { ?>
                                                            <?php $sum += $SavedDynamicBoxval; ?>
                                                            <?php
                                                        }
                                                    }
                                                }
                                            }
                                            ?>
                                            <?php if ($sum == 0) { ?>

                                                <td class="plus_minus">
                                                    <a class="incr-btn" data-action="decrease" data-group="<?php echo $DynamicBoxkey; ?>" href="javascript:;">–</a>
                                                    <input   readonly="" class="s_item l_item t_class" data-max="50"  data-group="<?php echo $DynamicBoxkey; ?>"  type="text" name="tempons_sum" value="<?php echo ((array_key_exists($category, $DynamicBoxval) && !is_null($DynamicBoxval[$category])) ? $DynamicBoxval[$category] : 0); ?>"/>
                                                    <a class="incr-btn" data-action="increase" data-group="<?php echo $DynamicBoxkey; ?>" href="javascript:;">&plus;</a>
                                                </td>

                                            <?php } else { ?>

                                                <td class="plus_minus" style="display: none;">
                                                    <a class="incr-btn" data-action="decrease" data-group="<?php echo $DynamicBoxkey; ?>" href="javascript:;">–</a>
                                                    <input readonly="" class="s_item l_item t_class" data-max="50" data-group="<?php echo $DynamicBoxkey; ?>" name="tempons_sum" value="<?php echo ((array_key_exists($category, $DynamicBoxval) && !is_null($DynamicBoxval[$category])) ? $DynamicBoxval[$category] : 0); ?>" type="text">
                                                    <a class="incr-btn inactive" data-action="increase" data-group="1" href="javascript:;">+</a>
                                                </td>

                                                <td class="gCatQuantity"><span class="gCatQuantitySelected" id=""><?php echo $sum; ?></span>/<span class="gCatQuantityTotal"><?php echo ((array_key_exists($category, $DynamicBoxval) && !is_null($DynamicBoxval[$category])) ? $DynamicBoxval[$category] : 0); ?></span></td>

                                            <?php } ?>

                                            <td class="choosebtn"><a href="javascript:;" data-val="<?php echo $category; ?>" data-group="<?php echo $DynamicBoxkey; ?>" class="ajaxTrigger" > Choose Tampons</a></td>
                                        </tr>
                                        <?php
                                        //echo '<pre>'.var_export($DynamicBoxes, true).'</pre>';
                                        //echo '<pre>'.var_export($SavedDynamicBoxes, true).'</pre>';
                                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                        $productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
                                        ?>

                                        <?php if ($SavedDynamicBoxes) { ?>
                                            <?php if (array_key_exists($DynamicBoxkey, $SavedDynamicBoxes)) { ?>
                                                <?php if (array_key_exists($category, $SavedDynamicBoxes[$DynamicBoxkey])) { ?>
                                                    <?php foreach ($SavedDynamicBoxes[$DynamicBoxkey][$category] as $pId => $SavedDynamicBoxval) { ?>
                                                        <?php
                                                        $product = $productRepository->getById($pId);
                                                        $brand = $product->getResource()->getAttribute('brand')->getFrontend()->getValue($product);
                                                        $absorbancy = $product->getResource()->getAttribute('absorbency')->getFrontend()->getValue($product);
                                                        ?>
                                                        <tr id="item-<?php echo $pId; ?>_append" class="tr-popup <?php echo $category; ?>_append_child <?php
                                                        echo $brand . " ";
                                                        echo $absorbancy ? "absorbancy " : " ";
                                                        echo $product->getData('long') ? "long " : " ";
                                                        echo $product->getData('deodorant') ? "deodorant " : " ";
                                                        echo $product->getData('scented') ? "scented " : " ";
                                                        echo $product->getData('with_baking_soda') ? "baking_soda " : " ";
                                                        echo $product->getData('wings') ? "wings " : " ";
                                                        ?>" data-group="<?php echo $DynamicBoxkey; ?>">
                                                            <td class="carefree-title">
                                                                <span><img src="https://www.mytavia.com/beta/pub/media/catalog/product/cache/thumbnail/75x75/beff4985b56e3afdbeabfc89641a4582<?php echo $product->getData('image'); ?>"></span>
                                                                <h4><strong><?php echo $brand; ?></strong> <?php echo $product->getData('name'); ?></h4>
                                                                <span class="responsive_show_icons">
                                                                    <span class="showinresponsive">
                                                                        <?php if ($absorbancy) { ?>
                                                                            <span class="tooltiptitle">Absorbancy</span>
                                                                            <img src="https://www.mytavia.com/beta/pub/static/version1510299952/frontend/Magento/coustomTheme/en_US/images/<?php echo $absorbancy; ?>.png">
                                                                        <?php } ?>
                                                                    </span>
                                                                    <span class="showinresponsive"></span>
                                                                </span>
                                                            </td>

                                                            <td class="plus_minus">
                                                                <a class="incr-btn-selection" data-action="decrease" href="javascript:;" data-title="<?php echo $category; ?>_append">–</a>
                                                                <input class="l_item s_item-append" data-max="" data-id="option-<?php echo $pId; ?>" name="itemSelected[<?php echo $pId; ?>]" value="<?php echo $SavedDynamicBoxval; ?>" data-group="<?php echo $DynamicBoxkey; ?>" data-category="<?php echo $category; ?>" readonly="readonly" type="text">
                                                                <a class="inactive incr-btn-selection" data-action="increase" href="javascript:;" data-title="<?php echo $category; ?>_append">+</a>
                                                            </td>
                                                            <td class="carefree-icon remove-icons">
                                                                <span class="hideinresponsive">
                                                                    <?php if ($absorbancy) { ?>
                                                                        <span class="tooltiptitle">Absorbancy</span>
                                                                        <img src="https://www.mytavia.com/beta/pub/static/version1510299952/frontend/Magento/coustomTheme/en_US/images/<?php echo $absorbancy; ?>.png">
                                                                    <?php } ?>
                                                                </span>
                                                                <span class="hideinresponsive">
                                                                    <?php if ($product->getData('scented')) { ?>
                                                                        <span class="tooltiptitle" >Scented</span>
                                                                        <img src="https://www.mytavia.com/beta/pub/static/version1509969426/frontend/Magento/coustomTheme/en_US/images/carefree-icon-2.png">

                                                                    <?php } ?>
                                                                    <?php if ($product->getData('deodorant')) { ?>
                                                                        <span class="tooltiptitle" >Deodorant</span>
                                                                        <img src="https://www.mytavia.com/beta/pub/static/version1509969426/frontend/Magento/coustomTheme/en_US/images/carefree-icon-3.png">
                                                                    <?php } ?>
                                                                </span>
                                                                <span><a class="deletebtn showinresponsive" data-title="<?php echo $category; ?>_append" href="javascript:;" id="item-<?php echo $pId; ?>_app">×</a></span>
                                                            </td>
                                                        </tr>
                                                        <?php
                                                    }
                                                }
                                            }
                                        }
                                        ?>


                                        <tr class="ttl_cls Pads_append"  data-class="Pads_append" data-group="<?php echo $DynamicBoxkey; ?>">
                                            <td class="title-block">
                                                <span><img src="<?php echo $this->getViewFileUrl('images/create-icon-3.png'); ?>"></span>Pads
                                            </td>

                                            <?php $category = 'Pads'; ?>
                                            <?php
                                            $sum = 0;
                                            $cat = 'Pads';
                                            if ($SavedDynamicBoxes) {
                                                ?>
                                                <?php if (array_key_exists($DynamicBoxkey, $SavedDynamicBoxes)) { ?>
                                                    <?php if (array_key_exists($category, $SavedDynamicBoxes[$DynamicBoxkey])) { ?>
                                                        <?php foreach ($SavedDynamicBoxes[$DynamicBoxkey][$category] as $pId => $SavedDynamicBoxval) { ?>
                                                            <?php $sum += $SavedDynamicBoxval; ?>
                                                            <?php
                                                        }
                                                    }
                                                }
                                            }
                                            ?>
                                            <?php if ($sum == 0) { ?>

                                                <td class="plus_minus">
                                                    <a class="incr-btn" data-action="decrease" data-group="<?php echo $DynamicBoxkey; ?>" href="javascript:;">–</a>
                                                    <input   readonly="" class="s_item l_item t_class" data-max="50"  data-group="<?php echo $DynamicBoxkey; ?>"  type="text" name="tempons_sum" value="<?php echo ((array_key_exists($cat, $DynamicBoxval) && !is_null($DynamicBoxval[$cat])) ? $DynamicBoxval[$cat] : 0); ?>"/>
                                                    <a class="incr-btn" data-action="increase" data-group="<?php echo $DynamicBoxkey; ?>" href="javascript:;">&plus;</a>
                                                </td>

                                            <?php } else { ?>

                                                <td class="plus_minus" style="display: none;">
                                                    <a class="incr-btn" data-action="decrease" data-group="<?php echo $DynamicBoxkey; ?>" href="javascript:;">–</a>
                                                    <input readonly="" class="s_item l_item t_class" data-max="50" data-group="<?php echo $DynamicBoxkey; ?>" name="pads_sum" value="<?php echo ((array_key_exists($cat, $DynamicBoxval) && !is_null($DynamicBoxval[$cat])) ? $DynamicBoxval[$cat] : 0); ?>" type="text">
                                                    <a class="incr-btn inactive" data-action="increase" data-group="1" href="javascript:;">+</a>
                                                </td>

                                                <td class="gCatQuantity"><span class="gCatQuantitySelected" id=""><?php echo $sum; ?></span>/<span class="gCatQuantityTotal"><?php echo ((array_key_exists($cat, $DynamicBoxval) && !is_null($DynamicBoxval[$cat])) ? $DynamicBoxval[$cat] : 0); ?></span></td>

                                            <?php } ?>

                                            <!--td class="plus_minus">
                                                <a class="incr-btn" data-action="decrease" data-group="<?php echo $DynamicBoxkey; ?>" href="javascript:;">–</a>
                                                <input  readonly="" class="s_item l_item p_class" data-max="50"  data-group="<?php echo $DynamicBoxkey; ?>"  type="text" name="pads_sum" value="<?php echo ((array_key_exists($category, $DynamicBoxval) && !is_null($DynamicBoxval[$category])) ? $DynamicBoxval[$category] : 0 ); ?>"/>
                                                <a class="incr-btn" data-action="increase" data-group="<?php echo $DynamicBoxkey; ?>" href="javascript:;">&plus;</a>
                                            </td-->
                                            <td class="choosebtn"><a href="javascript:;" data-val="<?php echo $category; ?>" data-group="<?php echo $DynamicBoxkey; ?>" class="ajaxTrigger" >Choose Pads</a></td>
                                        </tr>

                                        <?php if ($SavedDynamicBoxes) { ?>
                                            <?php if (array_key_exists($DynamicBoxkey, $SavedDynamicBoxes)) { ?>
                                                <?php if (array_key_exists($category, $SavedDynamicBoxes[$DynamicBoxkey])) { ?>
                                                    <?php foreach ($SavedDynamicBoxes[$DynamicBoxkey][$category] as $pId => $SavedDynamicBoxval) { ?>
                                                        <?php
                                                        $product = $productRepository->getById($pId);
                                                        $brand = $product->getResource()->getAttribute('brand')->getFrontend()->getValue($product);
                                                        $absorbancy = $product->getResource()->getAttribute('absorbency')->getFrontend()->getValue($product);
                                                        ?>
                                                        <tr id="item-<?php echo $pId; ?>_append" class="tr-popup <?php echo $category; ?>_append_child <?php
                                                        echo $brand . " ";
                                                        echo $absorbancy ? "absorbancy " : " ";
                                                        echo $product->getData('long') ? "long " : " ";
                                                        echo $product->getData('deodorant') ? "deodorant " : " ";
                                                        echo $product->getData('scented') ? "scented " : " ";
                                                        echo $product->getData('with_baking_soda') ? "baking_soda " : " ";
                                                        echo $product->getData('wings') ? "wings " : " ";
                                                        ?>" data-group="<?php echo $DynamicBoxkey; ?>">
                                                            <td class="carefree-title">
                                                                <span><img src="https://www.mytavia.com/beta/pub/media/catalog/product/cache/thumbnail/75x75/beff4985b56e3afdbeabfc89641a4582<?php echo $product->getData('image'); ?>"></span>
                                                                <h4><strong><?php echo $brand; ?></strong> <?php echo $product->getData('name'); ?></h4>
                                                                <span class="responsive_show_icons">
                                                                    <span class="showinresponsive">
                                                                        <?php if ($absorbancy) { ?>
                                                                            <span class="tooltiptitle">Absorbancy</span>
                                                                            <img src="https://www.mytavia.com/beta/pub/static/version1510299952/frontend/Magento/coustomTheme/en_US/images/<?php echo $absorbancy; ?>.png">
                                                                        <?php } ?>
                                                                    </span>
                                                                    <span class="showinresponsive"></span>
                                                                </span>
                                                            </td>

                                                            <td class="plus_minus">
                                                                <a class="incr-btn-selection" data-action="decrease" href="javascript:;" data-title="<?php echo $category; ?>_append">–</a>
                                                                <input class="l_item s_item-append" data-max="" data-id="option-<?php echo $pId; ?>" name="itemSelected[<?php echo $pId; ?>]" value="<?php echo $SavedDynamicBoxval; ?>" data-group="<?php echo $DynamicBoxkey; ?>" data-category="<?php echo $category; ?>" readonly="readonly" type="text">
                                                                <a class="inactive incr-btn-selection" data-action="increase" href="javascript:;" data-title="<?php echo $category; ?>_append">+</a>
                                                            </td>
                                                            <td class="carefree-icon remove-icons">
                                                                <span class="hideinresponsive">
                                                                    <?php if ($absorbancy) { ?>
                                                                        <span class="tooltiptitle">Absorbancy</span>
                                                                        <img src="https://www.mytavia.com/beta/pub/static/version1510299952/frontend/Magento/coustomTheme/en_US/images/<?php echo $absorbancy; ?>.png">
                                                                    <?php } ?>
                                                                </span>
                                                                <span class="hideinresponsive">
                                                                    <?php if ($product->getData('scented')) { ?>
                                                                        <span class="tooltiptitle" >Scented</span>
                                                                        <img src="https://www.mytavia.com/beta/pub/static/version1509969426/frontend/Magento/coustomTheme/en_US/images/carefree-icon-2.png">

                                                                    <?php } ?>
                                                                    <?php if ($product->getData('deodorant')) { ?>
                                                                        <span class="tooltiptitle" >Deodorant</span>
                                                                        <img src="https://www.mytavia.com/beta/pub/static/version1509969426/frontend/Magento/coustomTheme/en_US/images/carefree-icon-3.png">
                                                                    <?php } ?>
                                                                </span>
                                                                <span><a class="deletebtn showinresponsive" data-title="<?php echo $category; ?>_append" href="javascript:;" id="item-<?php echo $pId; ?>_app">×</a></span>
                                                            </td>
                                                        </tr>
                                                        <?php
                                                    }
                                                }
                                            }
                                        }
                                        ?>

                                        <tr class="ttl_cls Liners_append"  data-class="Liners_append" data-group="<?php echo $DynamicBoxkey; ?>">
                                            <td class="title-block">
                                                <span><img src="<?php echo $this->getViewFileUrl('images/create-icon-4.png'); ?>"></span>Liners
                                            </td>
                                            <?php $category = 'Liners'; ?>
                                            <?php
                                            $sum = 0;
                                            $cat = 'Liners';
                                            if ($SavedDynamicBoxes) {
                                                ?>
                                                <?php if (array_key_exists($DynamicBoxkey, $SavedDynamicBoxes)) { ?>
                                                    <?php if (array_key_exists($category, $SavedDynamicBoxes[$DynamicBoxkey])) { ?>
                                                        <?php foreach ($SavedDynamicBoxes[$DynamicBoxkey][$category] as $pId => $SavedDynamicBoxval) { ?>
                                                            <?php $sum += $SavedDynamicBoxval; ?>
                                                            <?php
                                                        }
                                                    }
                                                }
                                            }
                                            ?>
                                            <?php if ($sum == 0) { ?>

                                                <td class="plus_minus">
                                                    <a class="incr-btn" data-action="decrease" data-group="<?php echo $DynamicBoxkey; ?>" href="javascript:;">–</a>
                                                    <input   readonly="" class="s_item l_item t_class" data-max="50"  data-group="<?php echo $DynamicBoxkey; ?>"  type="text" name="tempons_sum" value="<?php echo ((array_key_exists($cat, $DynamicBoxval) && !is_null($DynamicBoxval[$cat])) ? $DynamicBoxval[$cat] : 0); ?>"/>
                                                    <a class="incr-btn" data-action="increase" data-group="<?php echo $DynamicBoxkey; ?>" href="javascript:;">&plus;</a>
                                                </td>

                                            <?php } else { ?>

                                                <td class="plus_minus" style="display: none;">
                                                    <a class="incr-btn" data-action="decrease" data-group="<?php echo $DynamicBoxkey; ?>" href="javascript:;">–</a>
                                                    <input readonly="" class="s_item l_item t_class" data-max="50" data-group="<?php echo $DynamicBoxkey; ?>" name="liners_sum" value="<?php echo ((array_key_exists($cat, $DynamicBoxval) && !is_null($DynamicBoxval[$cat])) ? $DynamicBoxval[$cat] : 0); ?>" type="text">
                                                    <a class="incr-btn inactive" data-action="increase" data-group="1" href="javascript:;">+</a>
                                                </td>

                                                <td class="gCatQuantity"><span class="gCatQuantitySelected" id=""><?php echo $sum; ?></span>/<span class="gCatQuantityTotal"><?php echo ((array_key_exists($cat, $DynamicBoxval) && !is_null($DynamicBoxval[$cat])) ? $DynamicBoxval[$cat] : 0); ?></span></td>

                                            <?php } ?>

                                            <td class="choosebtn"><a href="javascript:;" data-val="Liners" data-group="<?php echo $DynamicBoxkey; ?>" class="ajaxTrigger" data-group="<?php echo $DynamicBoxkey; ?>" >Choose Liners</a></td>
                                        </tr>

                                        <?php if ($SavedDynamicBoxes) { ?>
                                            <?php if (array_key_exists($DynamicBoxkey, $SavedDynamicBoxes)) { ?>
                                                <?php if (array_key_exists($category, $SavedDynamicBoxes[$DynamicBoxkey])) { ?>
                                                    <?php foreach ($SavedDynamicBoxes[$DynamicBoxkey][$category] as $pId => $SavedDynamicBoxval) { ?>
                                                        <?php
                                                        $product = $productRepository->getById($pId);
                                                        $brand = $product->getResource()->getAttribute('brand')->getFrontend()->getValue($product);
                                                        $absorbancy = $product->getResource()->getAttribute('absorbency')->getFrontend()->getValue($product);
                                                        ?>
                                                        <tr id="item-<?php echo $pId; ?>_append" class="tr-popup <?php echo $category; ?>_append_child <?php
                                                        echo $brand . " ";
                                                        echo $absorbancy ? "absorbancy " : " ";
                                                        echo $product->getData('long') ? "long " : " ";
                                                        echo $product->getData('deodorant') ? "deodorant " : " ";
                                                        echo $product->getData('scented') ? "scented " : " ";
                                                        echo $product->getData('with_baking_soda') ? "baking_soda " : " ";
                                                        echo $product->getData('wings') ? "wings " : " ";
                                                        ?>" data-group="<?php echo $DynamicBoxkey; ?>">
                                                            <td class="carefree-title">
                                                                <span><img src="https://www.mytavia.com/beta/pub/media/catalog/product/cache/thumbnail/75x75/beff4985b56e3afdbeabfc89641a4582<?php echo $product->getData('image'); ?>"></span>
                                                                <h4><strong><?php echo $brand; ?></strong> <?php echo $product->getData('name'); ?></h4>
                                                                <span class="responsive_show_icons">
                                                                    <span class="showinresponsive">
                                                                        <?php if ($absorbancy) { ?>
                                                                            <span class="tooltiptitle">Absorbancy</span>
                                                                            <img src="https://www.mytavia.com/beta/pub/static/version1510299952/frontend/Magento/coustomTheme/en_US/images/<?php echo $absorbancy; ?>.png">
                                                                        <?php } ?>
                                                                    </span>
                                                                    <span class="showinresponsive"></span>
                                                                </span>
                                                            </td>

                                                            <td class="plus_minus">
                                                                <a class="incr-btn-selection" data-action="decrease" href="javascript:;" data-title="<?php echo $category; ?>_append">–</a>
                                                                <input class="l_item s_item-append" data-max="" data-id="option-<?php echo $pId; ?>" name="itemSelected[<?php echo $pId; ?>]" value="<?php echo $SavedDynamicBoxval; ?>" data-group="<?php echo $DynamicBoxkey; ?>" data-category="<?php echo $category; ?>" readonly="readonly" type="text">
                                                                <a class="inactive incr-btn-selection" data-action="increase" href="javascript:;" data-title="<?php echo $category; ?>_append">+</a>
                                                            </td>
                                                            <td class="carefree-icon remove-icons">
                                                                <span class="hideinresponsive">
                                                                    <?php if ($absorbancy) { ?>
                                                                        <span class="tooltiptitle">Absorbancy</span>
                                                                        <img src="https://www.mytavia.com/beta/pub/static/version1510299952/frontend/Magento/coustomTheme/en_US/images/<?php echo $absorbancy; ?>.png">
                                                                    <?php } ?>
                                                                </span>
                                                                <span class="hideinresponsive">
                                                                    <?php if ($product->getData('scented')) { ?>
                                                                        <span class="tooltiptitle" >Scented</span>
                                                                        <img src="https://www.mytavia.com/beta/pub/static/version1509969426/frontend/Magento/coustomTheme/en_US/images/carefree-icon-2.png">

                                                                    <?php } ?>
                                                                    <?php if ($product->getData('deodorant')) { ?>
                                                                        <span class="tooltiptitle" >Deodorant</span>
                                                                        <img src="https://www.mytavia.com/beta/pub/static/version1509969426/frontend/Magento/coustomTheme/en_US/images/carefree-icon-3.png">
                                                                    <?php } ?>
                                                                </span>
                                                                <span><a class="deletebtn showinresponsive" data-title="<?php echo $category; ?>_append" href="javascript:;" id="item-<?php echo $pId; ?>_app">×</a></span>
                                                            </td>
                                                        </tr>
                                                        <?php
                                                    }
                                                }
                                            }
                                        }
                                        ?>

                                        <!--tr class="days-bock">
                                            <td class="title-block">Send them every</td>
                                            <td class="plus_minus-days" colspan="2">
                                                <a class="incr-btn-days" data-action="decrease" href="javascript:;">–</a>
                                                <input class="s_item-days l_item" data-max=""  type="text" name="daysAfter" value="20"/>
                                                <a class="incr-btn-days" data-action="increase" href="javascript:;">&plus;</a> days
                                            </td>
                                        </tr-->
                                        </tbody>
                                    </table>
                                </div>
                                <?php
                                $ind++;
                                if ($show) {
                                    $show = false;
                                }
                            }
                            ?>
                            <table class="table table-box">
                                <tbody>
                                    <tr class="days-bock">
                                        <td class="title-block">Send them every</td>
                                        <td class="plus_minus-days" colspan="2">
                                            <a class="incr-btn-days" data-action="decrease" href="javascript:;">–</a>
                                            <input class="s_item-days l_item" data-max=""  type="text" name="daysAfter" id="daysAfter" value="<?php echo $SusbcriptionDays; ?>"/>
                                            <a class="incr-btn-days" data-action="increase" href="javascript:;">&plus;</a> days
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div><!--/menu2-->

        </div><!--/tab-content-->
    </div><!--/container-->

    <!--Footer-->
    <div class="footer-tab">
        <div class="container">
            <div class="tab-finner">

                <!--<form name="page1" action="" method="POST">-->
               <!--                <input type="hidden" name="tempons_sum" class="t_section_sum_val section_total" value="7">
                               <input type="hidden" name="pads_sum" class="p_section_sum_val section_total" value="7">
                               <input type="hidden" name="liners_sum" class="l_section_sum_val section_total" value="7">
                               <input type="hidden" name="total_sum" class="section_total_sum" value="21">-->
                <button type="submit" name="Submit" id="submitbtn">
                    <i class="fa fa-refresh fa-spin loadericon" style="display: none"></i> Submit <span><img src="<?php echo $this->getViewFileUrl('images/arrow-right-2.png'); ?>"></span>
                </button>

                <div class="footertab-block">
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="tab-fimg">
                                <img src="<?php echo $this->getViewFileUrl('images/tab-footer-img.png'); ?>">
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="tab-flink">
                                <h4>Your subscription supports the local economy </h4>
                                <ul class="list-unstyled">
                                    <li><a href="javascript:;">You get your subscription</a></li>
                                    <li><a href="javascript:;">You provide a solution to a girl</a></li>
                                    <li><a href="javascript:;">You provide a job to a woman so she can support her family </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>
<!-- Modal -->
<div id="myModal" class="modal fade pads-popup" role="dialog">
    <!--<div id="myModal" class="" role="dialog">-->
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <div class="row">
                    <div class="col-sm-4">
                        <h4 class="modal-title" >Choose pads</h4>
                    </div>
                    <div class="col-sm-4">
                        <h6 id="popupInfoTab" class="text_error"><span id="catItemSelected">0</span> of <span id="catBoxSize">0</span> products selected</h6>
                    </div>
                    <div class="col-sm-4">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <div class="choose-brand">
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="brand-select">
                                <select id="brandSelectId">
                                    <option value="all">All Brands</option>
                                    <!--                                                                        <option value="Always">Always</option>
                                                                                                            <option value="Carefree">Carefree</option>
                                                                                                            <option value="OB">O.B.</option>
                                                                                                            <option value="Playtex">Playtex</option>
                                                                                                            <option value="Stayfree">Stayfree</option>
                                                                                                            <option value="Tampax">Tampax</option>-->
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="brand-select">
                                <select id="absorbancSelectId">
                                    <option value="all">Any Absorbency</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="brand-srch">
                                <input id="searchId" type="text" placeholder="Search pads ">
                                <button id="searchId-btn"><i class="fa fa-search" aria-hidden="true"></i></button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="choose-category">
                    <ul class="list-inline clearfix">
                        <li id="wings">
                            <span><img src="<?php echo $this->getViewFileUrl('images/category-img-1.png'); ?>"></span>
                            <h4>Wings</h4>
                            <span class="close_tbtn">×</span>
                        </li>
                        <li id="long">
                            <span><img src="<?php echo $this->getViewFileUrl('images/category-img-2.png'); ?>"></span>
                            <h4>Long</h4>
                            <span class="close_tbtn">×</span>
                        </li>
                        <li id="deodorant">
                            <span><img src="<?php echo $this->getViewFileUrl('images/category-img-3.png'); ?>"></span>
                            <h4>Deodorant</h4>
                            <span class="close_tbtn">×</span>
                        </li>
                        <li id="scented">
                            <span><img src="<?php echo $this->getViewFileUrl('images/category-img-4.png'); ?>"></span>
                            <h4>Scented</h4>
                            <span class="close_tbtn">×</span>
                        </li>
                        <li id="baking_soda">
                            <span><img src="<?php echo $this->getViewFileUrl('images/category-img-5.png'); ?>"></span>
                            <h4>With baking soda</h4>
                            <span class="close_tbtn">×</span>
                        </li>
                    </ul>
                </div><!--/choose-category-->

                <div class="product-details customize-block ">
                    <div class="table-responsive ">
                        <div style="text-align:center">
                            <img src="https://www.mytavia.com/beta/pub/static/version1510122454/frontend/Magento/coustomTheme/en_US/images/loader-2.gif" id="loaderId">
                        </div>
                        <div id="emptyDivId" class="alert no-match alert-danger" style="display: none">
                            No result found matching the criteria  <a id="resetFilter" href="javascript:;"><strong>Reset Filters</strong></a>
                        </div>
                        <table class="table">
                            <tbody id="popupId">
                            </tbody>
                        </table>
                    </div>
                    <div class="add-pads">
                        <button data-dismiss="modal" id="addBtnId">Add selected pads</button>
                    </div>
                </div>
                <input type="hidden" value="" id="data-val-popup">
                <input type="hidden" value="" id="data-val-group">
            </div><!--/modal-body-->
        </div>
    </div>

    <script type="text/javascript">

        require(["jquery"], function ($) {
            var completeArray = null;
            $(document).ready(function () {
                $("#searchId-btn").click(function (e) {
                    e.preventDefault();
                })
                $("ul.nav.nav-tabs li").removeClass("active");
                $("ul.nav.nav-tabs li:eq(1)").addClass("active");
                $("ul.nav.nav-tabs li:eq(0) a").attr("href", "https://www.mytavia.com/beta/tavia/index/index");
                $(".page_no_change").text("2/4");
                $(".page_title_change").text("Create your customized box");
//                console.log($(".page.mesages").html());
                var messareprompt = $(".page.messages").html();
                $(".page.messages").remove();
                $("<div class='page messages'>" + messareprompt + "</div>").insertAfter(".tab-header");
//                $(".container-fluid").hide();

                $(".bundle-options-wrapper,#bundleSummary,.footer-main,.bundle-options-container").hide();
                $(".tab-header").show();
                //*************************************************************************************************************************************************
                // Creating Function for the
                //*************************************************************************************************************************************************

                function hideShow() {
                    $("#emptyDivId").hide();
                    var active_class_dot = "";
                    $.each($("ul.list-inline li.active"), function (key, value) {
                        active_class_dot = active_class_dot + "." + $(this).attr("id");
                    });
                    if ($("#brandSelectId").val() != "all") {
                        active_class_dot = active_class_dot + "." + $("#brandSelectId").val();
                    }
                    if ($("#absorbancSelectId").val() != "all") {
                        active_class_dot = active_class_dot + ".absorbancy" + $("#absorbancSelectId").val();
                    }
                    $.each($("#popupId tr"), function (key, value) {
                        if (active_class_dot.length != 0) {
                            if ($(this).is(active_class_dot)) {
                                $(this).show();
                            } else {
                                $(this).hide();
                            }
                        } else {
                            $(this).show();
                        }
                    });
                    if ($("tbody#popupId > tr:visible").length == 0) {
                        $("#emptyDivId").show();
                    }

                }
                $('#brandSelectId,#absorbancSelectId').change(function () {
                    hideShow();
                });
                //*************************************************************************************************************************************************
                // Reset Filter function for making the filters reset
                //*************************************************************************************************************************************************
                function resetFilter() {
                    $("#searchId").val("");
                    $("ul.list-inline li").removeClass("active");
                    $('#brandSelectId,#absorbancSelectId').prop('selectedIndex', 0);
                    $("#popupId tr").show();
                    $("#emptyDivId").hide();
                    $("#popupInfoTab").removeClass("success-cls");
                    //                    $("#catItemSelected").text("0");
                }

                //*************************************************************************************************************************************************
                // Setting the box size dropdown value according to the previous selection.
                //*************************************************************************************************************************************************

                var recomended = 0;
                var groupId = 0;
                $('.recomended-block .ttl_qty').each(function (e) {
                    groupId = $(this).data('group');
                    recomended = $(this).val();
                    if (recomended < 16) {
                        $('.box_size_id[data-group="' + groupId + '"]').val("15");
                        $(".bundle-option-185").parent(".field.choice").siblings(".field.choice").children("input.click_none").click();
                        var box_size = 15;
                    } else if (recomended < 21) {
                        $('.box_size_id[data-group="' + groupId + '"]').val("20");
                        $(".bundle-option-184").click();
                        var box_size = 20;
                    } else if (recomended < 26) {
                        $('.box_size_id[data-group="' + groupId + '"]').val("25");
                        $(".bundle-option-184").click();
                        var box_size = 25;
                    } else {
                        $('.box_size_id[data-group="' + groupId + '"]').val("50");
                        var box_size = 50;
                        $(".bundle-option-185").click();
                    }
                    $('.ttl_qty[data-group="' + groupId + '"]').attr("data-max", box_size);
                    $('.ttl_box_display_qty[data-group="' + groupId + '"]').text(box_size);
                    $('.ttl_display_added_qty[data-group="' + groupId + '"]').text(recomended);
                    if (recomended != box_size) {
                        $('.ajaxTrigger[data-group="' + groupId + '"]').addClass("prevent-popup");
                    }
                });
//                } else {
//                    var home_url = "<?php // echo $block->getUrl('tavia/index/index');        ?>";
//                    $(location).attr('href', home_url);
//                }

                //*************************************************************************************************************************************************
                // change the value of the box on chenge of dropdown
                //*************************************************************************************************************************************************

                $('.box_size_id').change(function (e) {
                    var group = $(this).data('group');
                    //fixed the mobile issue
                    $('.box_size_id[data-group="' + group + '"]').val($(this).val());
                    box_size = $('.box_size_id[data-group="' + group + '"]').val();
                    $('.ttl_qty[data-group="' + group + '"]').attr('data-max', box_size);
                    $('.ttl_box_display_qty[data-group="' + group + '"]').text(box_size);
                    if ($('.ttl_qty[data-group="' + group + '"]').val() > box_size) {
                        $('.ttl_display_added_qty[data-group="' + group + '"]').parent('div').addClass('alert-danger').removeClass('alert-info').removeClass('alert-success');
                        $('.ajaxTrigger[data-group="' + group + '"]').addClass('prevent-popup');
                    } else if ($('.ttl_qty[data-group="' + group + '"]').val() == box_size) {
                        $('.ttl_display_added_qty[data-group="' + group + '"]').parent('div').addClass('alert-success').removeClass('alert-info').removeClass('alert-danger');
                        $('.ajaxTrigger[data-group="' + group + '"]').removeClass('prevent-popup');
                    } else {
                        $('.ttl_display_added_qty[data-group="' + group + '"]').parent('div').addClass('alert-info').removeClass('alert-success').removeClass('alert-danger');
                        $('.ajaxTrigger[data-group="' + group + '"]').addClass('prevent-popup');
                    }
                });
                //*************************************************************************************************************************************************
                //Plus minus code or increment quantity code
                //*************************************************************************************************************************************************

                $(".dynamicboxlink").on("click", function (e) {
                    var group = $(this).data('group');
                    $('.dynamicboxwrap').hide();
                    $('.dynamicboxwrap[data-group="' + group + '"]').show();
                });
                $(".incr-btn").on("click", function (e) {
                    var $button = $(this);
                    var group = $(this).data('group');
                    var box_size = $('.box_size_id[data-group="' + group + '"]').val();
                    var oldValue = $button.parent().find('.s_item[data-group="' + group + '"]').val();
                    $button.parent().find('.incr-btn[data-action="decrease"]').removeClass('inactive');
                    if ($button.data('action') == "increase") {
                        var sum = parseInt($('.ttl_qty[data-group="' + group + '"]').val()) + parseInt(1);
                        if (sum <= box_size) {
                            var newVal = parseFloat(oldValue) + 1;
                        } else {
                            newVal = oldValue;
                            $button.addClass('inactive');
                            $('.ttl_display_added_qty[data-group="' + group + '"]').parent("div").addClass("alert-danger").removeClass("alert-success");
                        }
                    } else {
                        if (oldValue > 0) {
                            var newVal = parseFloat(oldValue) - 1;
                        } else {
                            newVal = 0;
                            $button.addClass('inactive');
                            $('.ttl_display_added_qty[data-group="' + group + '"]').parent("div").addClass("alert-danger").removeClass("alert-success");
                        }
                    }
                    $button.parent().find('.s_item[data-group="' + group + '"]').val(newVal);
                    var sum = 0;
                    $.each($('tr.ttl_cls td.plus_minus .s_item[data-group="' + group + '"]'), function (key, value) {
                        sum += +$(value).val();
                    });
                    $('.ttl_qty[data-group="' + group + '"]').val(sum);
                    $('.ttl_display_added_qty[data-group="' + group + '"]').text(sum);
                    if (sum == box_size) {
                        $('.ttl_display_added_qty[data-group="' + group + '"]').parent("div").addClass("alert-success").removeClass("alert-danger");
                        $('.ajaxTrigger[data-group="' + group + '"]').removeClass("prevent-popup");
                    } else {
                        $('.ttl_display_added_qty[data-group="' + group + '"]').parent("div").removeClass("alert-success").addClass("alert-danger");
                        $('.ajaxTrigger[data-group="' + group + '"]').addClass("prevent-popup");
                    }
                    e.preventDefault();
                });
                //*************************************************************************************************************************************************
                //Plus minus Days
                //*************************************************************************************************************************************************

                $(".incr-btn-days").on("click", function (e) {
                    var $button = $(this);
                    var oldValue = $button.parent().find('.s_item-days').val();
                    $button.parent().find('.incr-btn-days[data-action="decrease"]').removeClass('inactive');
                    if ($button.data('action') == "increase") {
                        /*var sum = parseInt($(".ttl_qty").val()) + parseInt(1);*/
                        if (oldValue < 120) {
                            var newVal = parseFloat(oldValue) + 1;
                        } else {
                            newVal = oldValue;
                            $button.addClass('inactive');
                        }
                    } else {
                        if (oldValue > 0) {
                            var newVal = parseFloat(oldValue) - 1;
                        } else {
                            newVal = 0;
                            $button.addClass('inactive');
                        }
                    }
                    $button.parent().find('.s_item-days').val(newVal);
                    e.preventDefault();
                });
                //*************************************************************************************************************************************************
                // Prevent Popup model from opening and opening of popup
                //*************************************************************************************************************************************************

                $(".ajaxTrigger").on("click", function (e) {
                    $('#addBtnId').hide();
                    var group = $(this).data('group');
                    $("#popupId").empty();
                    if ($(this).hasClass("prevent-popup")) {
                        $('.ttl_display_added_qty[data-group="' + group + '"]').parent("div").removeClass("alert-success").removeClass("alert-info").addClass("alert-danger");
                        e.stopPropagation();
                    } else {
                        if ($(this).parent(".choosebtn").siblings("td.plus_minus").children("input.s_item.l_item").val() == 0)
                        {
                            e.stopPropagation();
                        } else {
                            $(".pads-popup").toggleClass("open");
                            console.log("openpopup");
                            resetFilter();
                            $("#catItemSelected").text("0");
                            $('#ttl_box_display_qty[data-group="' + group + '"]').text();
                            var cat_max_size = $(this).parent("td").siblings("td.plus_minus").children(".s_item").val();
                            $("#catBoxSize").text(cat_max_size);
                            $("#loaderId").show();
                            $('.ttl_display_added_qty[data-group="' + group + '"]').parent("div").removeClass("alert-danger").removeClass("alert-info").addClass("alert-success");
                            var catRequest = $(this).attr("data-val");
                            $('#brandSelectId').find('option').remove();
                            if (catRequest == "Tampons") {
                                $('#brandSelectId').append('<option value="all">All Brands</option>');
                                $('#brandSelectId').append('<option value="OB">O.B.</option>');
                                $('#brandSelectId').append('<option value="Playtex" >Playtex</option>');
                                $('#brandSelectId').append('<option value="Tampax" >Tampax</option>');
                            } else if (catRequest == "Pads") {
                                $('#brandSelectId').append('<option value="all" >All Brands</option>');
                                $('#brandSelectId').append('<option value="Always">Always</option>');
                                $('#brandSelectId').append('<option value="Playtex">Playtex</option>');
                                $('#brandSelectId').append('<option value="Stayfree">Stayfree</option>');
                            } else {
                                $('#brandSelectId').append('<option value="all" >All Brands</option>');
                                $('#brandSelectId').append('<option value="Always" >Always</option>');
                                $('#brandSelectId').append('<option value="Carefree" >Carefree</option>');
                                $('#brandSelectId').append('<option value="Playtex" >Playtex</option>');
                            }
                            $(".modal-title").text("Choose " + catRequest);
                            $("#searchId").attr("placeholder", "Search " + catRequest);
                            $("#addBtnId").text("Add Selected " + catRequest);
                            $("#data-val-popup").val(catRequest);
                            $("#data-val-group").val(group);
                            //*************************************************************************************************************************************************
                            //Ajax code for the brands selection
                            //*************************************************************************************************************************************************

                            var customurl = "<?php echo $this->getUrl() . 'tavia/index/popup/' ?>";
                            $.ajax({
                                url: customurl,
                                type: 'POST',
                                dataType: 'json',
                                data: {
                                    catRequest: catRequest,
                                },
                                complete: function (response) {
                                    $("#loaderId").hide();
                                    $("#popupId").html(response.responseText);
                                    completeArray = JSON.parse($("#completeArrayId").val());
                                },
                                error: function (xhr, status, errorThrown) {
                                    console.log('Error happens. Try again.');
                                }
                            });
                        }
                    }
                });
                //*************************************************************************************************************************************************
                // Toggel Filters for popup
                //*************************************************************************************************************************************************

                $('ul.list-inline li').click(function () {

                    if ($(this).closest('li').hasClass("active")) {
                        $(this).closest('li').removeClass('active');
                    } else {
                        $(this).closest('li').addClass('active');
                    }
                    hideShow();
                });
                //*************************************************************************************************************************************************
                // Reset Filters
                //*************************************************************************************************************************************************

                $("#resetFilter").click(function () {
                    resetFilter();
                });
                //*************************************************************************************************************************************************
                //Plus minus code of append popup
                //*************************************************************************************************************************************************

                $(document).on("click", ".incr-btn-popup", function (e) {
                    var $button = $(this);
                    var oldValue = $button.parent().find('.s_item-popup').val();
                    $button.parent().find('.incr-btn-popup[data-action="decrease"]').removeClass('inactive');
                    if ($button.data('action') == "increase") {
                        var box_size_popup = $("#catBoxSize").text();
                        var sum_popup_cal = parseInt($("#catItemSelected").text()) + parseInt(1);
                        if (sum_popup_cal <= box_size_popup) {
                            var newVal = parseFloat(oldValue) + 1;
                        } else {
                            newVal = oldValue;
                            $button.addClass('inactive');
                        }
                    } else {
                        if (oldValue > 0) {
                            var newVal = parseFloat(oldValue) - 1;
                        } else {
                            newVal = 0;
                            $button.addClass('inactive');
                        }
                    }
                    $button.parent().find('.s_item-popup').val(newVal);
                    var sum_popup = 0;
                    $.each($("tr.tr-popup td.plus_minus input.s_item-popup"), function (key, value) {
                        sum_popup += +$(value).val();
                    });
                    $("#catItemSelected").text(sum_popup);
                    if (sum_popup == box_size_popup) {
                        $('#addBtnId').show();
                        $("td.plus_minus input.s_item-popup").removeClass("box_error");
                        $("#popupInfoTab").addClass("success-cls");
                        $("#addBtnId").removeClass("prevent-popup-add");
                    } else {
                        $('#addBtnId').hide();
                        $("#popupInfoTab").removeClass("success-cls");
                        $("#addBtnId").addClass("prevent-popup-add");
                    }
                    e.preventDefault();
                });
                //*************************************************************************************************************************************************
                //Popup items sellection append code
                //*************************************************************************************************************************************************
                $("#addBtnId").click(function (e) {
                    var group = $("#data-val-group").val();
                    e.preventDefault();
                    var catItemSelected = $("#catItemSelected").text();
                    var catBoxSize = $("#catBoxSize").text();
                    if (catItemSelected == catBoxSize) {
                        $("td.plus_minus input.s_item-popup").removeClass("box_error"); // Remove the error class from boxes
                        var catagoryId = $("#data-val-popup").val();
                        var AppendCatagoryClass = '.' + catagoryId + '_append[data-group="' + group + '"]';
                        var AppendCatagoryChildClass = catagoryId + '_append_child[data-group="' + group + '"]';
                        $(AppendCatagoryClass).find("td.gCatQuantity").remove(); // Remove the previous gCatQuantity td
                        $("table.table-box tr." + AppendCatagoryChildClass).remove(); // Remove the previous Selections
                        console.log(AppendCatagoryChildClass);
                        $("<td class='gCatQuantity'><span class='gCatQuantitySelected' id=''>" + catItemSelected + "</span>/<span class='gCatQuantityTotal' >" + catItemSelected + "</span></td>").insertAfter($(AppendCatagoryClass).find("td.plus_minus")); // Hiding the plus minus of catogory

                        $(".options-list." + catagoryId + "_name").children(".field.choice").children(".options-list").removeClass(catagoryId + "_name");
                        $(".options-list." + catagoryId + "_name").children(".field.choice").children("input.click_none").click();

                        $.each($("tr.tr-popup td.plus_minus input.s_item-popup"), function (key, value) {
                            $(value).attr('data-group', group);
                            $(value).attr('data-category', catagoryId);
                            if ($(value).val() > 0) {
                                $(".bundle-" + $(value).attr("data-id")).click();
                                $(".bundle-" + $(value).attr("data-id") + "-qty").val($(value).val()).change();
                                $(".bundle-" + $(value).attr("data-id")).parent(".field.choice").parent(".options-list").addClass(catagoryId + "_name");
                                $(value).removeClass("s_item-popup").addClass("s_item-append").attr('readonly', true);
                                $(value).siblings("a.incr-btn-popup").addClass("incr-btn-selection").removeClass("incr-btn-popup").attr("data-title", catagoryId + "_append");
                                $(value).parent("td.plus_minus").parent("tr.tr-popup").removeAttr("style");
                                var itemId = $(value).parent("td.plus_minus").parent("tr.tr-popup").attr("id");
                                var trashId = itemId + "_app";                                              // Id of the append row delete button
                                var appendItemId = itemId + "_append";                                      // Id of the append row
                                $(value).parent("td.plus_minus").siblings("td.remove-icons").children("span").addClass("hideinresponsive");
                                $(value).parent("td.plus_minus").siblings("td.carefree-icon.hideicons").remove();
                                $(value).parent("td.plus_minus").siblings("td.carefree-title").children("span.responsive_show_icons").children("span.hideinresponsive").addClass("showinresponsive").removeClass("hideinresponsive");
                                $(value).parent("td.plus_minus").siblings("td.remove-icons").append("<span><a class='deletebtn showinresponsive' data-title='" + catagoryId + "_append' href='javascript:;' id='" + trashId + "'>×</a></span>");
                                $(value).parent("td").parent("tr").attr("id", appendItemId);
                                var trVar = $(value).parent("td").parent("tr");
                                trVar.attr('data-group', group);
                                $(AppendCatagoryClass).find("td.plus_minus").hide(); // Hiding the plus minus of catogory
                                $(trVar).insertAfter(AppendCatagoryClass);
                            }
                        });
                        $(".pads-popup").toggleClass("open");
                    } else {
                        $("#popupId tr td.plus_minus input.s_item-popup").addClass("box_error");
                        e.preventDefault();
                        e.stopImmediatePropagation();
                        return false;
                    }
                });

                function addItemsInSession() {
                    $('.loadericon1').show();
                    var mainarray = [];
                    var optionId = 0, optionVal = 0, containerVal = 0;
                    var category = '';
                    $('.dynamicboxwrap').each(function (e) {
                        containerVal = 0
                        var temparray1 = {};
                        var temparray2 = {};
                        var temparray3 = {};
                        var temparray4 = [];
                        groupwrap = $(this).data('group');

                        category1 = 'Tampons';
                        $('.s_item-append[data-group="' + groupwrap + '"][data-category="' + category1 + '"]').each(function (e) {
                            optionVal = $(this).val();
                            optionId = $(this).data('id');
                            optionId = optionId.replace("option-", "");
                            //category = $(this).parent().find('.incr-btn-selection[data-action="decrease"]').attr('data-title');
                            temparray1[optionId.replace("option-", "")] = optionVal;
                        });
                        category2 = 'Pads';
                        $('.s_item-append[data-group="' + groupwrap + '"][data-category="' + category2 + '"]').each(function (e) {
                            optionVal = $(this).val();
                            optionId = $(this).data('id');
                            optionId = optionId.replace("option-", "");
                            //category = $(this).parent().find('.incr-btn-selection[data-action="decrease"]').attr('data-title');
                            temparray2[optionId.replace("option-", "")] = optionVal;
                        });
                        category3 = 'Liners';
                        $('.s_item-append[data-group="' + groupwrap + '"][data-category="' + category3 + '"]').each(function (e) {
                            optionVal = $(this).val();
                            optionId = $(this).data('id');
                            optionId = optionId.replace("option-", "");
                            //category = $(this).parent().find('.incr-btn-selection[data-action="decrease"]').attr('data-title');
                            temparray3[optionId.replace("option-", "")] = optionVal;
                        });
                        if ($('.box_size_id[data-group="' + groupwrap + '"]').val() == 20) {
                            containerVal = 20;
                        } else if ($('.box_size_id[data-group="' + groupwrap + '"]').val() == 25) {
                            containerVal = 25;
                        } else if ($('.box_size_id[data-group="' + groupwrap + '"]').val() == 50) {
                            containerVal = 50;
                        } else {
                            containerVal = 15;
                        }
                        temparray4['containersize'] = containerVal;
                        mainarray[groupwrap] = {Tampons: temparray1, Pads: temparray2, Liners: temparray3, size: temparray4};
                    });
                    $.ajax({
                        url: "<?php echo $this->getUrl() . 'tavia/index/saved/' ?>",
                        type: 'POST',
                        dataType: 'json',
                        data: {q: mainarray},
                        complete: function (response) {
                            window.location.href = "<?php echo $this->getUrl() . 'tavia/' ?>";
                            $('.loadericon1').hide();
                        },
                        error: function (xhr, status, errorThrown) {
                            console.log('Error happens. Try again.');
                        }
                    });
                }
                $(document).on("click", ".addextrabox", function (e) {
                    e.preventDefault();
                    addItemsInSession();
                    //window.location.href = "<?php echo $this->getUrl() . 'tavia/' ?>";
                });

                //*************************************************************************************************************************************************
                // Trash Button code
                //*************************************************************************************************************************************************

                $(document).on("click", ".deletebtn", function (e) {
                    var groupTr = $(this).parent("span").parent("td.carefree-icon").parent("tr.tr-popup").data('group');
                    $(this).parent("span").parent("td.carefree-icon").parent("tr.tr-popup").remove();
                    var sum_selection = 0;
                    var catName = $(this).attr("data-title");
                    $.each($('tr.' + catName + '_child[data-group="' + groupTr + '"] td.plus_minus input.s_item-append'), function (key, value) {
                        console.log($(value).val());
                        sum_selection += +$(value).val();
                    });
                    $('tr.' + catName + '[data-group="' + groupTr + '"] td.gCatQuantity span.gCatQuantitySelected').text(sum_selection);
                });
                //*************************************************************************************************************************************************
                //Plus minus code of final selection
                //*************************************************************************************************************************************************

                $(document).on("click", ".incr-btn-selection", function (e) {
                    var $button = $(this);
                    var grp = $button.parent().parent().data('group');
                    var catName = $button.attr('data-title');
                    var oldValue = $button.parent().find('.s_item-append').val();
                    $button.parent().find('.incr-btn-popup[data-action="decrease"]').removeClass('inactive');
                    if ($button.data('action') == "increase") {
                        var box_size_popup = $('tr.' + catName + '[data-group="' + grp + '"] td.gCatQuantity span.gCatQuantityTotal').text();
                        console.log("tr." + catName + " td.gCatQuantity span.gCatQuantityTotal");
                        console.log(box_size_popup);
                        var sum_popup_cal = parseInt($('tr.' + catName + '[data-group="' + grp + '"] td.gCatQuantity span.gCatQuantitySelected').text()) + parseInt(1);
                        if (sum_popup_cal <= box_size_popup) {
                            var newVal = parseFloat(oldValue) + 1;
                        } else {
                            newVal = oldValue;
                            $button.addClass('inactive');
                        }
                    } else {
                        if (oldValue > 1) {
                            var newVal = parseFloat(oldValue) - 1;
                        } else {
                            newVal = 1;
                            $button.addClass('inactive');
                        }
                    }
                    $button.parent().find('.s_item-append').val(newVal);
                    var sum_selection = 0;
                    $.each($('tr.' + catName + '_child[data-group="' + grp + '"] td.plus_minus input.s_item-append'), function (key, value) {
                        console.log($(value).val());
                        sum_selection += +$(value).val();
                    });
                    $('tr.' + catName + '[data-group="' + grp + '"] td.gCatQuantity span.gCatQuantitySelected').text(sum_selection);
                });
                //*************************************************************************************************************************************************
                //Search Funcnality
                //*************************************************************************************************************************************************

                $(document).on('keyup', '#searchId', function (e) {
                    var resultArr = [];
                    $("tr.tr-popup").hide();
                    for (var i in completeArray) {
                        if ((completeArray[i].name.toLowerCase()).indexOf($(this).val().toLowerCase()) > -1) {
                            resultArr.push(completeArray[i].id);
                        }
                    }
                    for (var j in resultArr) {
                        $("tr#item-" + resultArr[j]).show();
                    }
                });
                //*************************************************************************************************************************************************
                // Validating on click of submit btn
                //*************************************************************************************************************************************************

                $("#submitbtn,#secondBox").click(function (e) {
                    $(".loadericon").show();
                    var sum = 0, box_size = 0, groupwrap = 0, optionId = 0, optionVal = 0, containerVal = 0;
                    var childCls = '', optionName = '', checkName = '';
                    var mainarray = [];
                    var flag = true;
//                    alert("a");
                    $('.dynamicboxwrap').each(function (e) {
                        containerVal = 0
                        var temparray = {};
                        groupwrap = $(this).data('group');
                        box_size = $('.box_size_id[data-group="' + groupwrap + '"]').val();
                        sum = 0;
                        $('tr.ttl_cls[data-group="' + groupwrap + '"] span.gCatQuantitySelected').each(function (e) {
                            sum = parseInt(sum) + parseInt($(this).text());
                        });
                        if (box_size != sum) {
                            flag = false;
                        }
                        //else{
                        $('.s_item-append[data-group="' + groupwrap + '"]').each(function (e) {
                            optionVal = $(this).val();
                            optionId = $(this).data('id');
                            optionName = $('.bundle-' + optionId + '-qty').attr('name');
                            checkName = optionName.replace("_qty", "");
                            temparray[optionName] = optionVal;
                            temparray[checkName] = $('.bundle-' + optionId).val();
                            //console.log(optionId);
                            //console.log(optionName);
                            //console.log(optionVal);
                            //console.log(temparray);
                        });

                        temparray['bundle_option[<?php echo $boxOptionId; ?>]'] = $('.box_size_id[data-group="' + groupwrap + '"] option:selected').data('id');
                        temparray['bundle_option_qty[<?php echo $boxOptionId; ?>]'] = 1;
                        //}
                        mainarray[groupwrap] = temparray;

                    });
                    console.log(mainarray);
                    if (flag) {
                        var cartUrl = $('#product_addtocart_form').attr('action');
                        var boxLength = mainarray.length - 1;
                        var indNum = -1;
                        for (var key in mainarray) {
                            var itemObj = {};
                            itemObj['product'] = $('[name="product"]').val();
                            itemObj['form_key'] = $('[name="form_key"]').val();
                            itemObj['qty'] = 1;
                            itemObj['selected_configurable_option'] = '';
                            itemObj['related_product'] = '';
                            Object.assign(itemObj, mainarray[key]);
                            //$('.radio.product.bundle.option.change-container-classname').each(function (e) {
                            //itemObj[$(this).attr('name')] = '';
                            //});
                            //console.log(itemObj);
                            //console.log(itemObj);
                            //console.log('new');
                            $.ajax({
                                url: cartUrl,
                                type: 'POST',
                                dataType: 'json',
                                data: itemObj,
                                complete: function (response) {
                                    indNum++;
                                    //console.log('newres');
                                    var res = JSON.parse(response.responseText).backUrl;
                                    if (res.indexOf('checkout/cart') !== -1) {
                                        if (boxLength == indNum) {
                                            $.ajax({
                                                url: "<?php echo $this->getUrl() . 'tavia/index/display/' ?>",
                                                type: 'POST',
                                                dataType: 'json',
                                                data: {reset: 1, days: $('#daysAfter').val()},
                                                complete: function (response) {
                                                    window.location.href = res;
                                                },
                                                error: function (xhr, status, errorThrown) {
                                                    console.log('Error happens. Try again.');
                                                }
                                            });
                                        }
                                    } else {
                                        $(".loadericon").hide();
                                        alert('There is problem in submission. Please try again');
                                        window.location.href = res;
                                    }
                                },
                                error: function (xhr, status, errorThrown) {
                                    console.log('Error happens. Try again.');
                                }
                            });
                        }
                    } else {

                        $(".loadericon").hide();
                        alert("Please Choose the sub Items");
                    }
                    e.preventDefault();
                });
//*************************************************************************************************************************************************
// Close Model
//*************************************************************************************************************************************************

                $(".modal-header .close").click(function () {
                    $(".pads-popup").toggleClass("open");
                });
//*************************************************************************************************************************************************
// Popup Enable number Entry
//*************************************************************************************************************************************************

                $(document).on("change keyup", ".s_item-popup", function () {
//                    var changed_value = $(this).val();
                    var box_size_popup = $("#catBoxSize").text();
//                    var catItemSelected = $("#catItemSelected").text();
//                    var total_available = parseInt(box_size_popup) - parseInt(catItemSelected);
                    console.log(sum_popup);
                    var sum_popup = 0;
                    $.each($("tr.tr-popup td.plus_minus input.s_item-popup"), function (key, value) {
                        sum_popup += +$(value).val();
                    });
                    if (sum_popup > box_size_popup) {
                        $(this).addClass("box_error");
                        $(this).val(0);
                    } else {
                        $("td.plus_minus input.s_item-popup").removeClass("box_error");
                        $("#catItemSelected").text(sum_popup);
                        if (sum_popup == box_size_popup) {
                            $("#addBtnId").show();
                            console.log("show btn");
                            $("td.plus_minus input.s_item-popup").removeClass("box_error");
                            $("#popupInfoTab").addClass("success-cls");
                            $("#addBtnId").removeClass("prevent-popup-add");
                        } else {
                            $("#addBtnId").hide();
                            console.log("hide btn");
                            $("#popupInfoTab").removeClass("success-cls");
                            $("#addBtnId").addClass("prevent-popup-add");
                        }
                    }
//
//
                });
//*************************************************************************************************************************************************
// Popup Alphabets Disable
//*************************************************************************************************************************************************

                $(document).on('keydown', '.s_item-popup,.s_item-append', function (e) {
                    if ((e.which >= 48 && e.which <= 57) || (e.which >=
                            96 && e.which <= 105) || (e.which == 8) || (e.which == 46)) {
                        return e.which;
                    } else {
                        return false;
                    }
                });

            }); //document.ready End.
        })
                ; //Jquery box End.

    </script>
</div>
<div class="product_detail_hide" style="display:none">
    <?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')): ?>
        <div class="product info detailed">
            <?php $layout = $block->getLayout(); ?>
            <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
                <?php foreach ($detailedInfoGroup as $name): ?>
                    <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                    ?>
                    <div class="data item title"
                         aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias; ?>-title"
                         data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias; ?>">
                        <a class="data switch"
                           tabindex="-1"
                           data-toggle="switch"
                           href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                           id="tab-label-<?php /* @escapeNotVerified */ echo $alias; ?>-title">
                               <?php /* @escapeNotVerified */ echo $label; ?>
                        </a>
                    </div>
                    <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
                        <?php /* @escapeNotVerified */ echo $html; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
</div>